#pragma once
#include <iostream>
#include <cmath>
#include <algorithm>
#include <functional>
#include <memory>
#include <fstream> 
#include <sstream>

#include <string>
#include <thread>
#include <stack>
#include <deque>
#include <array>
#include <vector>
#include <set>
#include <map>
#include <unordered_set>
#include <unordered_map>